#!/bin/sh
# the next line restarts using tclsh \
exec tclsh "$0" ${1+"$@"}

package require Tcl 8.6
package require pdn

# Input = Macro-packed DEF (currently from innovus)
# Output = Def with PDN

pdn init [lindex $argv 0]

puts "##Power Delivery Network Generator: Generating PDN DEF"
set ::start_time [clock clicks -milliseconds]

pdn power_grid
pdn output_def

puts "Total walltime to generate PDN DEF = [expr {[expr {[clock clicks -milliseconds] - $::start_time}]/1000.0}] seconds"


puts "Macro-packed input def is $FpOutDef"
puts "##TASK 8 Final DEF generation with PDN : Stitching macro-packed DEF with SPECIAL NETS"

set cmd "exec def_gen $::FpOutDef [pdn get config def_output] $::design ${::design}_post_T8.def"
eval $cmd

puts "Total walltime till final DEF stitching = [expr {[expr {[clock clicks -milliseconds] - $::start_time}]/1000.0}] seconds"

