# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

proc source_pdn {dir} {
    if {[package vcompare [package present Tcl] 8.6] == -1} {
        source [file join $dir tcl8p5.tcl]
    }
    source [file join $dir pg_grid_procs.tcl]
    source [file join $dir gen_blockage.tcl]
    source [file join $dir opendb_writer.tcl]
    source [file join $dir create_pg_grid.tcl]
}

package ifneeded pdn 0.2.0 [list source_pdn $dir]
