# subdir and objects in current dir
SUBDIRS	= 
OBJECTS	= FlexTA.o FlexTA_init.o FlexTA_assign.o FlexTA_end.o FlexTA_rq.o


all:subdirs ${OBJECTS}

	
clean:cleansubdirs
	rm -f ${OBJECTS}
	
include ${MAKEINCLUDE}
