# subdir and objects in current dir
SUBDIRS	= 
OBJECTS	= frDRC_init.o frDRC_setup.o  frDRC_main.o  frDRC_util.o

all:subdirs ${OBJECTS}

	
clean:cleansubdirs
	rm -f ${OBJECTS}
	
include ${MAKEINCLUDE}
