# subdir and objects in current dir
SUBDIRS	= 
OBJECTS	= FlexDR.o FlexGridGraph.o FlexDR_init.o FlexDR_maze.o FlexDR_end.o FlexDR_conn.o FlexDR_rq.o FlexGridGraph_maze.o


all:subdirs ${OBJECTS}

	
clean:cleansubdirs
	rm -f ${OBJECTS}
	
include ${MAKEINCLUDE}
